name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bzwboy/ci-demo:$(date +%H%M)
      
    - name: Push image to docker hub
      run: docker push bzwboy/ci-demo:$(date +%H%M)
